"""Executor Agent — PyQGIS 脚本注入执行与闭环自愈验证."""

from __future__ import annotations

import hashlib
import json
import os
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from src.agents.architect_agent import ExecutionPlan, WorkflowNode
from src.agents.environment_agent import EnvironmentContext
from src.core.feedback_loop import FeedbackLoop, ErrorParser
from src.core.qgis_controller import QGISController, ProcessResult
from src.utils.logger import get_logger

logger = get_logger(__name__)


@dataclass
class OutputFile:
    """执行输出的单个文件."""

    path: str
    size_bytes: int
    format: str
    sha256: str = ""
    feature_count: int = 0

    def verify_hash(self) -> bool:
        """验证文件完整性."""
        if not Path(self.path).exists():
            return False
        if self.sha256:
            actual = hashlib.sha256(
                Path(self.path).read_bytes()
            ).hexdigest()
            return actual == self.sha256
        return True


@dataclass
class ExecutionResult:
    """Executor Agent 的完整执行结果."""

    success: bool
    output_files: list[OutputFile] = field(default_factory=list)
    error_summary: str = ""
    retry_count: int = 0
    token_cost: int = 0
    elapsed_sec: float = 0.0
    total_tokens: int = 0
    execution_history: list[dict] = field(default_factory=list)
    self_healing_log: list[dict] = field(default_factory=list)
    node_results: dict[str, ProcessResult] = field(default_factory=dict)

    def summary(self) -> str:
        """生成可读的摘要."""
        lines = [
            "=" * 60,
            f"  Execution {'✓ SUCCESS' if self.success else '✗ FAILED'}",
            "=" * 60,
            f"  输出文件: {len(self.output_files)} 个",
            f"  重试次数: {self.retry_count}",
            f"  Token 消耗: {self.total_tokens:,}",
            f"  耗时: {self.elapsed_sec:.1f}s",
        ]
        if self.error_summary:
            lines.append(f"  错误摘要: {self.error_summary}")
        for f in self.output_files:
            size_kb = f.size_bytes / 1024
            lines.append(
                f"  → {f.path} ({size_kb:.1f} KB, {f.format})"
            )
        return "\n".join(lines)


class ExecutorAgent:
    """执行者 Agent — 脚本注入 + 闭环验证.

    核心职责:
    1. 将 ExecutionPlan 编译为可执行的 PyQGIS Python 脚本
    2. 注入到 QGIS Python 子进程执行
    3. 捕获错误 → 自动分类 → 修正 → 重试 (Self-Healing)
    4. 验证输出文件完整性（哈希校验 / 要素数检查）
    """

    # 脚本模板
    SCRIPT_HEADER = """# -*- coding: utf-8 -*-
# Auto-generated by Geo-OpenClaw Executor Agent
# DO NOT EDIT MANUALLY

import sys, os, json, hashlib, traceback

OUTPUT_DIR = os.environ.get("GEO_CLAW_OUTPUT_DIR", ".")
RESULTS = {{"success": True, "outputs": [], "errors": []}}

try:
    from qgis.core import (
        QgsApplication, QgsVectorLayer, QgsRasterLayer,
        QgsProject, QgsGeometry, QgsFeature, QgsField
    )
    QGIS_AVAILABLE = True
    app = QgsApplication([], False)
    app.initQgis()
except Exception as e:
    QGIS_AVAILABLE = False
    RESULTS["errors"].append(f"QGIS init failed: {e}")

from osgeo import gdal, ogr, osr
import numpy as np

def _sha256(path):
    return hashlib.sha256(open(path, "rb").read()).hexdigest()

def _save_result(path, metadata):
    """记录输出文件及其元数据"""
    if os.path.exists(path):
        RESULTS["outputs"].append({{
            "path": path,
            "size_bytes": os.path.getsize(path),
            "sha256": _sha256(path),
            "metadata": metadata,
        }})

"""

    SCRIPT_FOOTER = """

# ── Finalize ──
if QGIS_AVAILABLE:
    app.exitQgis()

report_path = os.path.join(OUTPUT_DIR, "_execution_report.json")
with open(report_path, "w", encoding="utf-8") as f:
    json.dump(RESULTS, f, indent=2, ensure_ascii=False)

print(f"\\n[Geo-OpenClaw] Report saved to {report_path}")
sys.exit(0 if RESULTS["success"] else 1)
"""

    def __init__(self, max_retries: int = 3):
        self.max_retries = max_retries
        self.qgis_ctrl = QGISController()
        self.feedback_loop = FeedbackLoop(qgis_controller=self.qgis_ctrl)
        self.error_parser = ErrorParser()

    def execute(
        self,
        plan: ExecutionPlan,
        env: EnvironmentContext,
    ) -> ExecutionResult:
        """执行完整的地理处理工作流.

        Parameters
        ----------
        plan : ExecutionPlan
            Architect Agent 生成的工作流
        env : EnvironmentContext
            Environment Agent 配置的运行时上下文

        Returns
        -------
        ExecutionResult
        """
        t0 = time.time()
        logger.info(f"Executor Agent 开始执行 {len(plan.workflow_nodes)} 个节点")

        # 编译整个工作流为单个 PyQGIS 脚本
        script = self._compile_script(plan, env)

        # 执行并自愈
        result = self.feedback_loop.run(script, env.env_vars)

        token_cost = len(script) * 2 + 500  # 估算

        if result.success:
            return self._parse_success(result, plan, t0, token_cost)
        else:
            return self._parse_failure(result, plan, t0, token_cost)

    def _compile_script(
        self,
        plan: ExecutionPlan,
        env: EnvironmentContext,
    ) -> str:
        """将 ExecutionPlan 编译为 PyQGIS Python 脚本.

        每个 WorkflowNode 映射为一段函数调用，
        按拓扑排序串联，自动处理输入/输出传递。
        """
        lines = [self.SCRIPT_HEADER]

        ordered = plan.topological_order()

        # 用于存储中间结果的变量名映射
        var_map: dict[str, str] = {}

        for i, node in enumerate(ordered):
            lines.append(f"\n# {'=' * 50}")
            lines.append(f"# Node {i + 1}/{len(ordered)}: {node.id}")
            lines.append(f"# Skill: {node.skill}")
            lines.append(f"# Description: {node.description}")
            lines.append(f"# {'=' * 50}")

            try:
                node_script = self._node_to_script(node, var_map, env)
                lines.append(node_script)
                var_map[node.id] = f"_output_{node.id}"
            except Exception as e:
                lines.append(f"# [ERROR] Failed to compile node: {e}")
                lines.append(
                    f"RESULTS['errors'].append('Compile error at {node.id}: {e}')\n"
                    f"RESULTS['success'] = False"
                )

        lines.append(self.SCRIPT_FOOTER)
        return "\n".join(lines)

    def _node_to_script(
        self,
        node: WorkflowNode,
        var_map: dict[str, str],
        env: EnvironmentContext,
    ) -> str:
        """将单个 WorkflowNode 转换为 Python 代码片段."""
        skill = node.skill
        params = node.params
        out_var = f"_output_{node.id}"
        out_path = f"${{OUTPUT_DIR}}/{node.id}_output"

        # 解析输入引用
        input_refs = {}
        for dep_id in node.depends_on:
            if dep_id in var_map:
                input_refs["data"] = var_map[dep_id]

        if skill == "raster_load":
            pattern = params.get("pattern", node.inputs.get("pattern", "*.tif"))
            return f"""
# Raster Load: {pattern}
import glob
_files = glob.glob("{pattern}")
if not _files:
    RESULTS["errors"].append("No raster files found: {pattern}")
    RESULTS["success"] = False
else:
    print(f"Found {{len(_files)}} raster files")
    {out_var} = _files
"""

        elif skill == "vector_load":
            vpath = params.get("path", node.inputs.get("path", "input.shp"))
            return f"""
# Vector Load: {vpath}
{out_var} = QgsVectorLayer("{vpath}", "{node.id}", "ogr")
if not {out_var}.isValid():
    RESULTS["errors"].append("Failed to load: {vpath}")
    RESULTS["success"] = False
else:
    print(f"Loaded {{ {out_var}.featureCount() }} features")
"""

        elif skill == "reprojection":
            target = params.get("target_crs", "EPSG:3857")
            input_var = var_map.get(node.depends_on[0], "None") if node.depends_on else "None"
            return f"""
# Reprojection to {target}
import processing
{out_var} = processing.run("native:reprojectlayer", {{
    "INPUT": {input_var},
    "TARGET_CRS": QgsCoordinateReferenceSystem("{target}"),
    "OUTPUT": "{out_path}.gpkg",
}})["OUTPUT"]
print(f"Reprojected to {target}: {{ {out_var}.featureCount() }} features")
_save_result("{out_path}.gpkg", {{"skill": "reprojection", "crs": "{target}"}})
"""

        elif skill in ("raster_clip", "vector_clip"):
            input_var = var_map.get(node.depends_on[0], "None") if node.depends_on else "None"
            mask_var = var_map.get(node.depends_on[1], "mask") if len(node.depends_on) > 1 else "mask"
            return f"""
# Clip operation
import processing
{out_var} = processing.run("native:clip", {{
    "INPUT": {input_var},
    "OVERLAY": {mask_var},
    "OUTPUT": "{out_path}.gpkg",
}})["OUTPUT"]
print(f"Clipped: {{ {out_var}.featureCount() }} features")
_save_result("{out_path}.gpkg", {{"skill": "clip"}})
"""

        elif skill == "buffer_analysis":
            input_var = var_map.get(node.depends_on[0], "None") if node.depends_on else "None"
            dist = params.get("distance", 1000)
            segs = params.get("segments", 30)
            return f"""
# Buffer Analysis: {dist}m, {segs} segments
import processing
{out_var} = processing.run("native:buffer", {{
    "INPUT": {input_var},
    "DISTANCE": {dist},
    "SEGMENTS": {segs},
    "OUTPUT": "{out_path}.gpkg",
}})["OUTPUT"]
print(f"Buffer created: {{ {out_var}.featureCount() }} features")
_save_result("{out_path}.gpkg", {{"skill": "buffer", "distance": {dist}}})
"""

        elif skill == "spatial_join":
            a_var = var_map.get(node.depends_on[0], "layer_a") if node.depends_on else "layer_a"
            b_var = var_map.get(node.depends_on[1], "layer_b") if len(node.depends_on) > 1 else "layer_b"
            return f"""
# Spatial Join
import processing
{out_var} = processing.run("native:joinattributesbylocation", {{
    "INPUT": {a_var},
    "JOIN": {b_var},
    "PREDICATE": [0],  # intersects
    "METHOD": 0,  # one-to-one
    "OUTPUT": "{out_path}.gpkg",
}})["OUTPUT"]
print(f"Spatial Join: {{ {out_var}.featureCount() }} features")
_save_result("{out_path}.gpkg", {{"skill": "spatial_join"}})
"""

        elif skill == "export":
            fmt = params.get("format", "GeoPackage")
            input_var = var_map.get(node.depends_on[0], "None") if node.depends_on else "None"
            ext = {"GeoJSON": "geojson", "ESRI Shapefile": "shp",
                   "GeoPackage": "gpkg", "GeoTIFF": "tif"}.get(fmt, "gpkg")
            return f"""
# Export to {fmt}
import processing
export_path = "{out_path}.{ext}"
{out_var} = processing.run("native:savefeatures", {{
    "INPUT": {input_var},
    "OUTPUT": export_path,
}})["OUTPUT"]
print(f"Exported to {{export_path}}")
_save_result(export_path, {{"skill": "export", "format": "{fmt}"}})
"""

        else:
            # 通用回退 — 记录未知 skill 并继续
            return f"""
# Unknown skill: {skill} — using passthrough
print(f"Warning: unknown skill {{ {skill} }}, passing through")
{out_var} = None
"""

    def _parse_success(
        self,
        result: ProcessResult,
        plan: ExecutionPlan,
        t0: float,
        token_cost: int,
    ) -> ExecutionResult:
        """解析成功执行结果."""
        output_files = []
        artifact_dir = result.artifact_dir

        if artifact_dir:
            for f in Path(artifact_dir).glob("*"):
                if f.name.startswith("_exec") or f.name.startswith("_"):
                    continue
                if f.is_file():
                    output_files.append(OutputFile(
                        path=str(f),
                        size_bytes=f.stat().st_size,
                        format=f.suffix.lstrip("."),
                    ))

        return ExecutionResult(
            success=True,
            output_files=output_files,
            retry_count=len(self.feedback_loop.heal_history),
            token_cost=token_cost,
            elapsed_sec=time.time() - t0,
        )

    def _parse_failure(
        self,
        result: ProcessResult,
        plan: ExecutionPlan,
        t0: float,
        token_cost: int,
    ) -> ExecutionResult:
        """解析失败执行结果，附带诊断信息."""
        diagnosis = self.error_parser.diagnose(result.stderr, result.stdout)

        return ExecutionResult(
            success=False,
            error_summary=(
                f"[{diagnosis.category.value}] {diagnosis.suggested_fix}\n"
                f"Exit code: {result.exit_code}\n"
                f"stderr: {result.stderr[:500]}"
            ),
            retry_count=len(self.feedback_loop.heal_history),
            token_cost=token_cost,
            elapsed_sec=time.time() - t0,
            self_healing_log=[
                {
                    "attempt": h.attempt,
                    "category": h.diagnosis.category.value,
                    "healed": h.healed,
                }
                for h in self.feedback_loop.heal_history
            ],
        )
